# Generated by Django 4.2.1 on 2023-06-19 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0004_remove_cita_especialidad_paciente_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='paciente',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='clinic.perfil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_doctor', to='clinic.perfil'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to='clinic.perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('PAC', 'Paciente'), ('DOC', 'Doctor')], default='PAC', max_length=3),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='clinic.perfil'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
