# Generated by Django 4.2.1 on 2023-06-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remove_paciente_user_remove_pregunta_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
